{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1726425414001, "stop": 1726425414530, "uuid": "20420639-b097-4e86-8714-65883c3d50c6", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "NB-ISC-69172.local"}, {"name": "thread", "value": "13839-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}